all:
	make -C helloworld
	make -C nomain
	make -C lightdemo
	make -C bathtub
	make -C calculator
	make -C counter
	make -C xultest
	make -C svgview

clean:
	make -C helloworld clean
	make -C nomain clean
	make -C lightdemo clean	
	make -C bathtub clean
	make -C calculator clean
	make -C counter clean   
	make -C xultest clean
	make -C svgview clean
